---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect1
  namespace: confluent
spec:
  replicas: 1
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub:
          - name: kafka-connect-syslog
            owner: confluentinc
            version: 1.5.2
  image:
    application: confluentinc/cp-server-connect:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  mountedSecrets:
    - secretRef: kafka-client-config-secure
  dependencies:
    kafka:
      bootstrapEndpoint: ${bootstrapEndpoint}
      authentication:
        type: plain
        jaasConfig:
          secretRef: cloud-plain
      tls:
        enabled: true
        ignoreTrustStoreConfig: true 
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect2
  namespace: confluent
spec:
  replicas: 1
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub:
          - name: kafka-connect-syslog
            owner: confluentinc
            version: 1.5.2
  image:
    application: confluentinc/cp-server-connect:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  mountedSecrets:
    - secretRef: kafka-client-config-secure
  dependencies:
    kafka:
      bootstrapEndpoint: ${bootstrapEndpoint}
      authentication:
        type: plain
        jaasConfig:
          secretRef: cloud-plain
      tls:
        enabled: true
        ignoreTrustStoreConfig: true 
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5454
      targetPort: 5454
  selector:
    platform.confluent.io/type: connect
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 10Gi
  authentication:
    type: basic
    basic:
      secretRef: control-center-user
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: my.domain
      prefix: rb-c3
  # known issue https://docs.confluent.io/operator/current/co-troubleshooting.html#issue-c3-cannot-use-auto-generated-certificates-for-mds-or-ccloud-sr
  configOverrides:
    server:
      - confluent.metrics.topic.max.message.bytes=8388608  
  dependencies:
    kafka:
      bootstrapEndpoint: ${bootstrapEndpoint}
      authentication:
        type: plain
        jaasConfig:
          secretRef: cloud-plain
      tls:
        enabled: true
        ignoreTrustStoreConfig: true 
    connect:
    - name: connect1
      url:  http://connect1.confluent.svc.cluster.local:8083
    - name: connect2
      url:  http://connect2.confluent.svc.cluster.local:8083
---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: syslog-connector1
spec:
  taskMax: 1
  class: "io.confluent.connect.syslog.SyslogSourceConnector"
  connectClusterRef:
    name: connect1
  configs:
    syslog.listener: "TCP"
    syslog.port: "5454"
    topic: "test_syslog"
---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: syslog-connector2
spec:
  taskMax: 1
  class: "io.confluent.connect.syslog.SyslogSourceConnector"
  connectClusterRef:
    name: connect2
  configs:
    syslog.listener: "TCP"
    syslog.port: "5454"
    topic: "test_syslog"
---
